### ISSUE TITLE
Implement Optmized Failed Extrinsic and Nonce handling Mechanism. 

### ISSUE THREAD

**Issue by jaxter03** [Polkadex-Substrate/polkadexTEE-worker#63] opened 2021-05-21 09:45 UTC

**Comment by haerdib** [comment] 2021-07-02 13:47
Hm - where's the problem here? Could you pin some assosciated code or explain what needs improvement?

**Comment by haerdib** [comment] 2021-10-25 07:11
closing this as a duplicate of #172

**Closed as completed by haerdib** 2021-10-25 07:11 UTC
Labels: duplicate
