### ISSUE TITLE
implement `withdraw`

### ISSUE THREAD

**Issue by brenzi** [Polkadex-Substrate/polkadexTEE-worker#12] opened 2021-04-29 17:52 UTC
there are two ways to withdraw: indirect or direct

# indirect

the enclave scans all new blocks from the chain-relay for relevant extrinsics. See:
https://github.com/scs/substraTEE-worker/blob/e2619abfff07a2fd9054fcbd4e23879cc0d0eba3/enclave/src/lib.rs#L778

We need to add the `ocex::withdraw` extrinsic to that list and trigger a withdrawal

# direct

depends on #2 

# withdraw flow

1. authenticate account permissions (proxy, main)
2. verify free balance is sufficient 
2. mutate balance
3. compose an `ocex::release` extrinsic, sign with enclave signing key and send it through ocall

**Comment by haerdib** [comment] 2021-05-11 16:52
Open question: for creating an ocex::release extrinsic in the enclave we need to know the current nonce of the chain. This is not an issue when doing it the indirect way. However, it is not as straight forward with a direct withdraw() call.

A simple solution coming to my mind is to store the current enclave nonce in memory within the enclave and increment with every composed extrinsic.

Or is there a different / better solution?

**Comment by brenzi** [comment] 2021-05-12 11:10
I think your suggestion is a sound solution

**Comment by Gauthamastro** [comment] 2021-05-14 11:54
@brenzi this solution can lead to inconsistent nonce in the enclave.

**Comment by Gauthamastro** [comment] 2021-05-14 12:01
We create a new field in the balance storage called "unconfirmed_balance" which is updated when the enclave gets a withdraw request and unconfirmed_balance is only mutated after enclave gets the confirmation that ocex::release has been executed. In this case, we can use the above solution.

**Comment by haerdib** [comment] 2021-05-14 12:36
@Gauthamastro  Order flow of extrinsics:

1. An extrinsic is created within the enclave in the [create_extrinsics](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/src/lib.rs#L197) function. The extrinsic is also [signed](https://github.com/Polkadex-Substrate/substrate-api-client/blob/master/src/extrinsic/mod.rs#L89) there. 
2. Every extrinsic is included in the [validator ](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/src/lib.rs#L433)(chain relay) by being  [pushed ](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/chain_relay/src/lib.rs#L203 ) to a [vector](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/chain_relay/src/state.rs#L33) of extrinsics, waiting for inclusion verification of the incoming finalized headers. 
3. Afterwards, the extrinsic is sent to the worker via [ocall](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/src/lib.rs#L444-L447). 
4. In the worker the extrinsics are finally [sent to the chain via api](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/worker/src/main.rs#L811).

**Comment by haerdib** [comment] 2021-05-17 10:16
We could store the the nonce in an atomic pointer, making it thread save. Simultaneous reads shoud not be allowed, because only one extrinsic can have a valid nonce.

With every finalized block (sync_chain) we get the chance to snyc the enclave nonce with the current onchain nonce. However, if we update with every block, there might occur wrong nonce updates, such as:

- enclave updates nonce correctly when issuing a ocex::release command, not yet processed by the  chain
- new finalized block: enclave "updates" nonce to old value
- the next read() of the enclave nonce will return the outdated value.

Is the above mentioned scenario acceptable? If not we could work with a flag NONCE_INVALID or something alike. This flag is set whenever an extrinsic is not accepted by the chain due to invalid nonce. Once it is set, the enclave will update its nonce with the next incoming block.
@brenzi , @Gauthamastro What are your thoughts on this?

**Comment by Gauthamastro** [comment] 2021-05-17 13:10
@haerdib @brenzi 
I am suggesting we create the following structure
```rust
pub struct nonce{
  confirmed_nonce: u64,
  unconfirmed_nonce: u64,
  unconfirmed_extrinsics: Vec<OpaqueCall>
}
```
and store it in an atomic pointer, during startup enclave sets confirmed_nonce as the nonce provided by the init_chain_relay and `use_unconfirmed_nonce = false`,  when enclave signs an extrinsic it will check if `unconfirmed_extrinsics.len()==0`then it will take confirmed_nonce and create the transaction, sets `unconfirmed_nonce=confirmed_nonce+1` and adds a copy of signed extrinsic to `unconfirmed_extrinsics`. If `unconfirmed_extrinsics.len() != 0` then enclave will use `unconfirmed_nonce` for signing the next extrincics.

Also, in the `sync_blocks` function, we look for the inclusion of extrinsics present in unconfirmed_extrinsics and update it. In case some extrinsics are missing, they will re-sent to the node for inclusion. 

What do you think about this?

**Comment by Gauthamastro** [comment] 2021-05-17 13:11
I believe it solves the nonce issue and takes care of weird race conditions too.

**Comment by brenzi** [comment] 2021-05-21 13:14
I have naming issues with you suggestion. let me rename:
```
pub struct PendingExtrinsics{
  last_included_nonce: u64,
  last_unconfirmed_nonce: u64,
  unconfirmed_extrinsics: Vec<OpaqueCall>
}
```

Still: there is actually no need for `last_included_nonce` as your test for `unconfirmed_extrinsics.len() != 0` is not necessary. I think we can reduce this to:

```
pub struct PendingExtrinsics{
  last_nonce: u64,  
  extrinsics: Vec<OpaqueCall>
}
```
At startup, you set last_nonce to onchain nonce.
With every extrinsic you increase.
If stored as an atomic pointer, this is thread-safe, but still limited to single instance of the gateway

Without further actions, pending extrinsics will be lost upon a crash unless they have made their way to the pool of a node

**Comment by jaxter03** [comment] 2021-05-25 16:12
@haerdib @Gauthamastro is there anything left that I can do in this issue?

**Comment by Gauthamastro** [comment] 2021-05-28 11:37
Yes, Closing this issue only since direct RPC call to implementation linking is remaining, which is taken care in a different issue

**Closed as completed by Gauthamastro** 2021-05-28 11:37 UTC
